import Head from "next/head";

import { Button, Input, Text } from "@mantine/core";

import axios from "axios";
import { useState } from "react";
import NovuBell from "../components/NovuBell";
import { showNotification } from "@mantine/notifications";

// Check From localstorage
export const getId = () => {
  if (typeof window !== "undefined") {
    let id1 = window.localStorage.getItem("id");

    if (!id1) {
      return null;
    }

    return id1;
  }
  return null;
};

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [id, setId] = useState("");
  const [idExists, setIdExists] = useState(false);

  // Send notification
  const sendNotification = async () => {
    setLoading(true);
    await axios
      .post("/api/", {
        subscriberId: `${getId()}`,
      })
      .then((res) => {
        setLoading(false);
        if (res?.status == 200) {
          showNotification({
            title: "Notification sent!",
            color: "green",
          });
        }
      })
      .catch((err) => {
        setLoading(false);
        showNotification({
          title: "An error occured",
          color: "red",
        });
      });
  };

  // Save ID
  const saveID = () => {
    if (!id) {
      showNotification({
        title: "No ID to save",
        message:
          "You need a unique username so that we know who to send the notification to.",
        autoClose: 3000,
        color: "orange",
      });
      return;
    }

    window.localStorage.setItem("id", id);
    showNotification({
      title: "Username saved",
      color: "green",
    });
    setIdExists(true);
  };

  return (
    <div>
      <Head>
        <title>Novu notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-between">
        <h1 className="font-semibold tracking-tight p-8">Notifications</h1>
        <div className="p-8 absolute top-2 right-0">
          <NovuBell subscriberId={getId()} />
        </div>
      </div>

      <div className="p-8 space-y-6">
        {getId() || idExists ? (
          <Button
            loading={loading}
            size="lg"
            color="dark"
            onClick={sendNotification}
            fullWidth
          >
            Send notification
          </Button>
        ) : (
          <>
            <Text color="dimmed">
              To receive notifications, type in a username of your choosing and
              click on get started{" "}
            </Text>
            <Input
              variant="filled"
              placeholder="Username eg. xyzp"
              size="lg"
              value={id}
              onChange={(e) => setId(e.target.value)}
            />
            <Button variant="light" size="lg" fullWidth onClick={saveID}>
              Get Started
            </Button>
          </>
        )}
      </div>
    </div>
  );
}
